name: "release"

# ============================
# Dispatchers 
# ============================
on:
  push:
    branches:
      - master

# ============================
# Repo permissions
# ============================

permissions:
  contents:      write
  pull-requests: write
  issues:        write

# ============================
# Jobs 
# ============================

jobs:

  # -------------
  # release
  # -------------
  release:
    # -- Metadata
    name:    Semantic Release
    runs-on: ubuntu-latest

    # -- Steps
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI_PROJECT_NAME: ${{ github.event.repository.name }}
      run: npx --no-install semantic-release --debug
